/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mark' at '9/28/16 8:52 AM' with Gradle 3.1
 *
 * @author mark, @date 9/28/16 8:52 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
