/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'mark' at '9/28/16 8:52 AM' with Gradle 3.1
 *
 * @author mark, @date 9/28/16 8:52 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
